[default]
KEYWORDS=["сбой", "не работает", "ошибка", '❗коллеги', '‼️коллеги,', '!!коллеги', '❗️коллеги', 'авария', '403', '504', '503', '502', 'устранена', 'устранено', 'исправлено', 'восстановлено', 'восстановлена']